### ISSUE TITLE
Docker image for running Elasticsearch configurable to run in the test environment.

### ISSUE THREAD

**Issue by tmcphillips** [openskope/skope-deployment#14]

**Comment by Zodiase** [comment]
The helper script I'm currently using to launch the elastic search instance on deployment server:

## `start-elastic.sh`

```Shell
#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# VERSION=docker.elastic.co/elasticsearch/elasticsearch:5.5.0
VERSION=elasticsearch:2

docker run --detach \
           --restart always \
           --name elasticsearch \
           --network apps-bridge \
           --publish 9200:9200 \
           --volume /mnt/mongo/elastic:/usr/share/elasticsearch/data \
           --volume $DIR/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml \
       $VERSION
```

## `elasticsearch.yml`

```YAML
http.host: 0.0.0.0
transport.host: 127.0.0.1

http.cors.enabled : true  
http.cors.allow-origin : "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length
```
